# Generated by Django 5.2.10 on 2026-03-06 04:39

import django.db.models.deletion
import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_invited_by_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('vpc_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster_arn', models.CharField(blank=True, max_length=512, null=True)),
                ('alb_arn', models.CharField(blank=True, max_length=512, null=True)),
                ('alb_dns', models.CharField(blank=True, max_length=512, null=True)),
                ('target_group_arn', models.CharField(blank=True, max_length=512, null=True)),
                ('ecr_repository_url', models.CharField(blank=True, max_length=512, null=True)),
                ('ecs_task_execution_role_arn', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('READY', 'Ready'), ('FAILED', 'Failed'), ('DESTROYING', 'Destroying')], default='PROVISIONING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='api.infrastructure')),
            ],
            options={
                'db_table': 'environments',
            },
        ),
    ]
