# Generated by Django 5.2.10 on 2026-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
