# Generated by Django 5.2.10 on 2026-03-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_environment_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='environment',
            new_name='environment_status_51e8a7_idx',
            old_name='environment_status_locked_idx',
        ),
    ]
