# Generated by Django 5.2.10 on 2026-03-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_environment_status_locked_idx_environment_status_51e8a7_idx'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='infrastructure',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='infrastructure',
            index=models.Index(fields=['user', 'is_cloud_authenticated'], name='api_infrast_user_id_e12281_idx'),
        ),
    ]
