# Generated by Django 5.2.10 on 2026-06-13 01:46

import django.db.models.deletion
import shared.utils.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_infrastructure_onboarding_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptApiKey',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRefreshEvent',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=32)),
                ('caller_arn', models.TextField(blank=True, default='')),
                ('script', models.CharField(default='update_aws_role.sh', max_length=64)),
                ('role_name', models.CharField(blank=True, default='', max_length=128)),
                ('policy_arn', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('infrastructure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_refresh_events', to='api.infrastructure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_refresh_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='pre_user_created_idx')],
            },
        ),
    ]
