# Generated by Django 5.2.10 on 2026-06-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_scriptapikey_policyrefreshevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='onboarding_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='onboarding_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
