# Generated by Django 5.2.10 on 2026-06-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_infrastructure_onboarding_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='is_mock',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
