# Generated by Django 5.2.10 on 2026-07-04 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_infrastructure_is_mock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrefreshevent',
            name='script',
            field=models.CharField(default='create_aws_role.sh', max_length=64),
        ),
    ]
