# Generated by Django 5.2.10 on 2026-08-29

from django.db import migrations, models
from django.db.models import F, Q


def backfill_first_activated_at(apps, schema_editor):
    """Stamp environments that ever produced real outputs as activated."""
    Environment = apps.get_model('api', 'Environment')
    Environment.objects.filter(first_activated_at__isnull=True).filter(
        Q(status='ACTIVE') | Q(vpc_id__isnull=False) | Q(cluster_arn__isnull=False)
    ).update(first_activated_at=F('updated_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_policyrefreshevent_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='first_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environment',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('PROVISIONING', 'Provisioning'),
                    ('ACTIVE', 'Active'),
                    ('UPDATING', 'Updating'),
                    ('ERROR', 'Error'),
                    ('DESTROYING', 'Destroying'),
                    ('DESTROYED', 'Destroyed'),
                ],
                default='PENDING',
                max_length=50,
            ),
        ),
        migrations.RunPython(backfill_first_activated_at, migrations.RunPython.noop),
    ]
