# Generated by Django 5.2.10 on 2026-08-30 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_environment_first_activated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='compute_type',
            field=models.CharField(choices=[('ecs_fargate', 'Ecs Fargate'), ('eks', 'Eks')], default='ecs_fargate', max_length=30),
        ),
    ]
