# Generated by Django 5.2.10 on 2026-08-30 17:06

import django.db.models.deletion
import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_environment_first_activated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('engine', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('redis', 'Redis'), ('docdb', 'DocumentDB')], max_length=16)),
                ('engine_version', models.CharField(max_length=16)),
                ('instance_class', models.CharField(max_length=32)),
                ('allocated_storage', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('ERROR', 'Error'), ('DELETING', 'Deleting'), ('DELETED', 'Deleted')], default='PENDING', max_length=20)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('secret_arn', models.CharField(blank=True, max_length=512, null=True)),
                ('final_snapshot_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='api.environment')),
            ],
            options={
                'db_table': 'databases',
                'indexes': [models.Index(fields=['environment', 'status'], name='databases_environ_a49c5a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'DELETED'), _negated=True), fields=('environment', 'name'), name='unique_live_database_name_per_environment')],
            },
        ),
    ]
