# Generated by Django 5.2.10 on 2026-09-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_database_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='policy_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
