# Generated by Django 5.2.10 on 2026-09-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_infrastructure_policy_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrefreshevent',
            name='policy_version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
