# Generated by Django 5.2.17 on 2026-09-07

import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_policyrefreshevent_policy_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedDnsLabel',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(db_index=True, max_length=16, unique=True)),
                ('infrastructure_id', models.UUIDField()),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='dns_label',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
