# Generated by Django 5.2.17 on 2026-09-07

import django.db.models.deletion
import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_infrastructure_dns_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDomain',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('DISABLED', 'Disabled')], default='PENDING', max_length=20)),
                ('cert_arn', models.CharField(blank=True, max_length=512, null=True)),
                ('aws_account_id', models.CharField(blank=True, max_length=32, null=True)),
                ('expires_at', models.DateTimeField()),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_domains', to='api.infrastructure')),
            ],
            options={
                'indexes': [models.Index(fields=['hostname', 'status'], name='api_customd_hostnam_de105d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'VALIDATED')), fields=('hostname',), name='unique_validated_custom_domain_hostname')],
            },
        ),
    ]
