# Generated by Django 5.2.10 on 2026-09-27 03:18

import django.db.models.deletion
import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_cost_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructure",
            name="dns_teardown_requested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InfrastructureCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=shared.utils.uuid.uuid7_pk,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cert_arn", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "validation_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "validation_value",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                (
                    "tls_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ISSUED", "Issued"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("tls_requested_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "infrastructure",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="api.infrastructure",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatformDnsRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=shared.utils.uuid.uuid7_pk,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("infrastructure_id", models.UUIDField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("edge", "Edge indirection"),
                            ("wildcard", "Wildcard to edge"),
                            ("validation", "ACM validation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("record_name", models.CharField(max_length=255)),
                ("record_type", models.CharField(default="CNAME", max_length=10)),
                ("record_value", models.CharField(max_length=512)),
                ("ttl", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["infrastructure_id"],
                        name="api_platfor_infrast_d34aca_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("infrastructure_id", "record_name", "record_type"),
                        name="unique_platform_dns_record_per_infra",
                    )
                ],
            },
        ),
    ]
