# Generated by Django 5.2.10 on 2026-09-27 (F1b part 2 — TLS activation)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_exit_export_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructurecertificate",
            name="tls_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ISSUED", "Issued"),
                    ("FAILED", "Failed"),
                    ("POLICY_STALE", "Policy stale"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="https_listener_arn",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="platformdnsrecord",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
