# Generated by Django 5.2.10 on 2026-09-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_f1b_tls_activation"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="eks_ingress_tls_ready",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="platformdnsrecord",
            name="change_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
