# Generated by Django 5.2.10 on 2026-09-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_f1b_host_readiness"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="eks_ingress_tls_cert_arn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="environment",
            name="eks_ingress_tls_patch_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
