# Generated by Django 5.2.10 on 2026-09-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_f1b_eks_tls_repatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructure",
            name="host_readiness_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
