# Generated by Django 5.2.10 on 2026-09-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_f1b_host_readiness_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdomain",
            name="application_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customdomain",
            name="ownership_token_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="customdomain",
            name="verification_failure_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="customdomain",
            index=models.Index(
                fields=["infrastructure", "application_id"],
                name="api_customd_infrast_c62ee6_idx",
            ),
        ),
    ]
