# Generated by Django 5.2.10 on 2026-09-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_custom_domain_hardening"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customdomain",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("VALIDATED", "Validated"),
                    ("DISABLING", "Disabling"),
                    ("DISABLED", "Disabled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
