# Generated by Django 5.2.10 on 2026-09-29 15:51

import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_custom_domain_disabling_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="NukeRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=shared.utils.uuid.uuid7_pk,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("infrastructure_id", models.UUIDField(db_index=True)),
                ("infrastructure_name", models.CharField(max_length=255)),
                ("user_id", models.UUIDField(db_index=True)),
                ("confirm_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("FAILED", "Failed"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("steps", models.JSONField(default=list)),
                ("leftovers", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "nuke_runs",
                "indexes": [
                    models.Index(
                        fields=["infrastructure_id", "created_at"],
                        name="nuke_infra_created_idx",
                    )
                ],
            },
        ),
    ]
