FROM python:3.11-slim AS base
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*

COPY deployment-services/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

FROM base AS final
COPY deployment-services/shared ./shared
COPY deployment-services/application-service .

ENV PYTHONPATH=/app
CMD ["python", "manage.py", "run_worker"]
