# Generated by Django 5.2.10 on 2026-01-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
