# Generated by Django 5.2.10 on 2026-01-25 17:56

import shared.utils.uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('alloted_cpu', models.FloatField(default=0.0)),
                ('alloted_memory', models.FloatField(default=0.0)),
                ('alloted_storage', models.FloatField(default=0.0)),
                ('project_remote_url', models.CharField(max_length=255)),
                ('project_branch', models.CharField(max_length=255)),
                ('project_commit_hash', models.CharField(max_length=255)),
                ('build_command', models.CharField(max_length=255)),
                ('start_command', models.CharField(max_length=255)),
                ('install_command', models.CharField(max_length=255)),
                ('envs', models.JSONField(blank=True, default=dict, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.infrastructure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
