# Generated by Django 5.2.10 on 2026-01-26 06:49

from django.db import migrations, models


def populate_names(apps, schema_editor):
    # H4 review: `str(infra.id)[:8]` is a UUIDv7 prefix, but `name` here is a purely
    # cosmetic display label on this service's own read-model copy of Infrastructure
    # (no unique constraint, never an AWS resource name or namespace key) — a display
    # collision between two rows backfilled in the same window is not a security issue.
    # This is also a historical, already-applied data migration; it is not edited to
    # use a different formula going forward; a real fix would live in a new migration.
    Infrastructure = apps.get_model('api', 'Infrastructure')
    for infra in Infrastructure.objects.filter(name__isnull=True):
        infra.name = f"infra-{str(infra.id)[:8]}"
        infra.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_application'),
    ]

    operations = [
        # Step 1: add column as nullable — IF NOT EXISTS is safe on both fresh
        # and prod DBs where the column already exists.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='infrastructure',
                    name='name',
                    field=models.CharField(max_length=255, null=True, default=None),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE api_infrastructure ADD COLUMN IF NOT EXISTS name varchar(255) NULL",
                    reverse_sql="ALTER TABLE api_infrastructure DROP COLUMN IF EXISTS name",
                ),
            ],
        ),
        # Step 2: populate name for any rows that have null (fresh installs or
        # prod rows that pre-dated the column)
        migrations.RunPython(populate_names, migrations.RunPython.noop),
        # Step 3: enforce NOT NULL now that every row has a value
        migrations.AlterField(
            model_name='infrastructure',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
