# Generated by Django 5.2.10 on 2026-01-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
