# Generated by Django 5.2.10 on 2026-01-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_infrastructure_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
