# Generated by Django 5.2.10 on 2026-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_application_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('guest', 'Guest'), ('super_admin', 'Super Admin')], default='user', max_length=20),
        ),
    ]
