# Generated by Django 5.2.10 on 2026-03-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='build_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='deployment_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='dockerfile_path',
            field=models.CharField(blank=True, default='Dockerfile', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='listener_rule_arn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='service_arn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('BUILDING', 'Building'), ('PUSHING_IMAGE', 'Pushing Image'), ('DEPLOYING', 'Deploying'), ('ACTIVE', 'Active'), ('FAILED', 'Failed')], default='CREATED', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='target_group_arn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='task_definition_arn',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='build_command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='install_command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='start_command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
