# Generated by Django 5.2.10 on 2026-03-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_update_application_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='port',
            field=models.IntegerField(default=8080),
        ),
    ]
