# Generated by Django 5.2.10 on 2026-03-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_unique_constraints'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='api_applica_user_id_6d458f_idx',
            old_name='api_applica_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='application',
            new_name='api_applica_status_57b6db_idx',
            old_name='api_applica_status_idx',
        ),
        migrations.RenameIndex(
            model_name='infrastructure',
            new_name='api_infrast_user_id_e12281_idx',
            old_name='api_infrast_user_id_auth_idx',
        ),
        migrations.RenameIndex(
            model_name='infrastructureuserrole',
            new_name='api_infrast_infrast_bad26b_idx',
            old_name='api_infrast_infrast_idx',
        ),
        migrations.RenameIndex(
            model_name='infrastructureuserrole',
            new_name='api_infrast_user_id_158172_idx',
            old_name='api_infrast_user_id_idx',
        ),
    ]
