# Generated by Django 5.2.10 on 2026-03-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_infrastructureuserrole'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'infrastructure', 'name')},
        ),
    ]
