# Generated by Django 5.2.10 on 2026-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_application_github_webhook_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='is_mock',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
