# Generated by Django 5.2.10 on 2026-07-05 18:41

import django.db.models.deletion
import shared.utils.uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_infrastructure_is_mock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureUserRole',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('guest', 'Guest'), ('super_admin', 'Super Admin')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='api.infrastructure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['infrastructure', 'user'], name='api_infrast_infrast_idx'), models.Index(fields=['user', 'role'], name='api_infrast_user_id_idx')],
                'unique_together': {('infrastructure', 'user')},
            },
        ),
    ]
