# Generated by Django 5.2.10 on 2026-08-30 17:30

import django.db.models.deletion
import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_infrastructure_user_role_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attached_database_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('engine', models.CharField(max_length=16)),
                ('host', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('secret_arn', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='api.environment')),
            ],
            options={
                'db_table': 'databases',
                'indexes': [models.Index(fields=['environment', 'status'], name='databases_environ_a49c5a_idx')],
            },
        ),
    ]
