# Generated by Django 5.2.10 on 2026-08-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_database_readmodel_and_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='compute_type',
            field=models.CharField(choices=[('ecs_fargate', 'Ecs Fargate'), ('eks', 'Eks')], default='ecs_fargate', max_length=30),
        ),
        migrations.AlterField(
            model_name='environment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROVISIONING', 'Provisioning'), ('ACTIVE', 'Active'), ('ERROR', 'Error'), ('DESTROYING', 'Destroying'), ('DESTROYED', 'Destroyed')], default='PENDING', max_length=50),
        ),
    ]
