# Generated by Django 5.2.17 on 2026-09-27 02:47

import django.db.models.deletion
import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_backfill_environment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="auto_deploy_paused",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=shared.utils.uuid.uuid7_pk,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_tag", models.CharField(max_length=255)),
                ("commit_sha", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "tag_source",
                    models.CharField(
                        choices=[
                            ("resolved_sha", "Resolved SHA"),
                            ("latest", "Latest (unpinned)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("compute_type", models.CharField(max_length=30)),
                ("env_keys", models.JSONField(default=list)),
                ("env_values_hash", models.CharField(max_length=64)),
                ("attached_database_ids", models.JSONField(default=list)),
                ("cpu", models.FloatField()),
                ("memory", models.FloatField()),
                ("port", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCEEDED", "Succeeded"), ("FAILED", "Failed")],
                        max_length=20,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[("DEPLOY", "Deploy"), ("ROLLBACK", "Rollback")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="api.application",
                    ),
                ),
                (
                    "rolled_back_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rollbacks",
                        to="api.deployment",
                    ),
                ),
            ],
            options={
                "db_table": "deployments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "-created_at"],
                        name="deployments_applica_82bcd2_idx",
                    )
                ],
            },
        ),
    ]
