# Generated by Django 5.2.17 on 2026-09-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_deployment_and_auto_deploy_paused"),
    ]

    operations = [
        migrations.AddField(
            model_name="deployment",
            name="image_digest",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
