# Generated by Django 5.2.10 on 2026-09-27
import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_deployment_image_digest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeLogAccess',
            fields=[
                ('id', models.UUIDField(default=shared.utils.uuid.uuid7_pk, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.CharField(max_length=36)),
                ('user_id', models.UUIDField()),
                ('app_id', models.UUIDField(blank=True, null=True)),
                ('infra_id', models.UUIDField(blank=True, null=True)),
                ('compute_type', models.CharField(blank=True, max_length=30, null=True)),
                ('container', models.CharField(blank=True, max_length=10, null=True)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('cursor_present', models.BooleanField(default=False)),
                ('status_code', models.IntegerField()),
                ('aws_error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('event_count', models.IntegerField(default=0)),
                ('bytes', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(default=0)),
                ('client_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'runtime_log_access',
                'indexes': [
                    models.Index(fields=['app_id', 'created_at'], name='runtime_log_app_id_e2f8a1_idx'),
                    models.Index(fields=['user_id', 'created_at'], name='runtime_log_user_id_8b3c4d_idx'),
                ],
            },
        ),
    ]
