# Generated by Django 5.2.10 on 2026-09-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_runtime_log_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="host_forward_rule_arn",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="application",
            name="host_route_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="dns_label",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="dns_synced",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="host_readiness_version",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="https_ready",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="infrastructure",
            name="tls_status",
            field=models.CharField(
                blank=True, editable=False, max_length=20, null=True
            ),
        ),
    ]
