# Generated by Django 5.2.10 on 2026-09-27 10:27

import shared.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_f1b_host_routing"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomDomainRoute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=shared.utils.uuid.uuid7_pk,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("infrastructure_id", models.UUIDField()),
                ("application_id", models.UUIDField()),
                ("hostname", models.CharField(max_length=255, unique=True)),
                ("cert_arn", models.CharField(max_length=512)),
                ("host_forward_rule_arn", models.CharField(max_length=512)),
                (
                    "host_redirect_rule_arn",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "custom_domain_routes",
                "indexes": [
                    models.Index(
                        fields=["application_id"], name="custom_doma_applica_4fc9fd_idx"
                    ),
                    models.Index(
                        fields=["infrastructure_id"],
                        name="custom_doma_infrast_33e83e_idx",
                    ),
                ],
            },
        ),
    ]
