# Generated by Django 5.2.10 on 2026-09-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_custom_domain_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="log_group_name",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
