# Generated by Django 5.2.10 on 2026-09-28 00:00

import re

from django.db import migrations
from django.db.models import Q


def _app_slug(name: str) -> str:
    # Duplicated from api/common/naming.py:app_slug, deliberately — a migration must
    # not import application code that can change independently of this historical
    # migration's own, fixed meaning. Keep in sync by hand if that function's regex
    # ever changes; a drift here only affects backfilled rows already deployed under
    # the legacy scheme, never a new deploy (which always calls the real function).
    return re.sub(r'[^a-z0-9._-]', '-', (name or '').lower()).strip('-')


def backfill_legacy_log_group_name(apps, schema_editor):
    """H4 review (R1): migration 0029 created the Deployment table with no backfill,
    and `_record_deployment` is best-effort (a history row failing to write never
    fails the deploy it describes) — so an app deployed before Deployment history
    existed, or whose own history row silently failed, can have neither a Deployment
    row nor `Application.log_group_name`. Left alone, `_create_task_definition` would
    read that as "never deployed" on its very next deploy and hand it a brand-new
    hashed log group, orphaning its actual runtime log history. Persists the exact
    legacy name (`/ecs/{slug}-task`) such a row's containers are already logging to —
    never a live rename — for any Application with a deployment_url, a task
    definition, a service, or any deployment history at all.

    `deployment_url` is checked first and matches
    `ApplicationDeploymentService._has_succeeded_before`'s own priority: it is set only
    by a fully successful deploy and `ApplicationRetryDeployView` never resets it
    (unlike `task_definition_arn`/`service_arn`, which it does), so it is the one
    signal immune to a retry queued in the window between this migration running and a
    worker picking up that retry's job."""
    Application = apps.get_model('api', 'Application')
    Deployment = apps.get_model('api', 'Deployment')

    deployed_app_ids = set(Deployment.objects.values_list('application_id', flat=True))

    candidates = Application.objects.filter(log_group_name__isnull=True).filter(
        (Q(deployment_url__isnull=False) & ~Q(deployment_url=''))
        | (Q(task_definition_arn__isnull=False) & ~Q(task_definition_arn=''))
        | (Q(service_arn__isnull=False) & ~Q(service_arn=''))
        | Q(id__in=deployed_app_ids)
    )
    for app in candidates.only('id', 'name'):
        app.log_group_name = f"/ecs/{_app_slug(app.name)}-task"
        app.save(update_fields=['log_group_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_application_log_group_name'),
    ]

    operations = [
        migrations.RunPython(backfill_legacy_log_group_name, migrations.RunPython.noop),
    ]
