# Generated by Django 5.2.10 on 2026-09-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_backfill_legacy_log_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructure",
            name="exited_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
