# Generated by Django 5.2.10 on 2026-09-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_encrypt_application_envs"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="task_family",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
