# Generated by Django 5.2.10 on 2026-09-28 00:00

import re

from django.db import migrations
from django.db.models import Q


def _app_slug(name: str) -> str:
    # Duplicated from api/common/naming.py:app_slug, deliberately — a migration must
    # not import application code that can change independently of this historical
    # migration's own, fixed meaning. Keep in sync by hand if that function's regex
    # ever changes; a drift here only affects backfilled rows already deployed under
    # the legacy scheme, never a new deploy (which always calls the real function).
    return re.sub(r'[^a-z0-9._-]', '-', (name or '').lower()).strip('-')


def backfill_legacy_task_family(apps, schema_editor):
    """H7 residual from H4: mirrors
    0035_backfill_legacy_log_group_name.py exactly, for `task_family` instead of
    `log_group_name` — same signals, same priority order, same reasoning
    (`_has_succeeded_before`'s deployment_url / ARN / Deployment-history checks), so a
    pre-existing app's ECS task family is never silently switched to the new hashed
    scheme out from under its running service."""
    Application = apps.get_model('api', 'Application')
    Deployment = apps.get_model('api', 'Deployment')

    deployed_app_ids = set(Deployment.objects.values_list('application_id', flat=True))

    candidates = Application.objects.filter(task_family__isnull=True).filter(
        (Q(deployment_url__isnull=False) & ~Q(deployment_url=''))
        | (Q(task_definition_arn__isnull=False) & ~Q(task_definition_arn=''))
        | (Q(service_arn__isnull=False) & ~Q(service_arn=''))
        | Q(id__in=deployed_app_ids)
    )
    for app in candidates.only('id', 'name'):
        app.task_family = f"{_app_slug(app.name)}-task"
        app.save(update_fields=['task_family'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_application_task_family'),
    ]

    operations = [
        migrations.RunPython(backfill_legacy_task_family, migrations.RunPython.noop),
    ]
