"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from pathlib import Path

from api.common.envs.application import app_config
from api.common.envs.database import DatabaseConfig
from api.validators import validate_eks_public_access_cidrs
from core.allowed_hosts_config import get_allowed_hosts
from shared.mode import is_dev_mode


# Validate critical configuration on startup
def validate_config():
    if not app_config.django_secret or len(app_config.django_secret) < 50:
        raise ValueError("DJANGO_SECRET must be set and at least 50 characters")
    # JWT_SECRET and INTERNAL_API_TOKEN are asserted ABSENT (not merely optional) for the
    # dns_writer role in ApplicationConfig.from_env() — skip the length checks here rather
    # than re-deriving that condition.
    if not app_config.is_dns_writer:
        if not app_config.jwt_secret or len(app_config.jwt_secret) < 32:
            raise ValueError("JWT_SECRET must be set and at least 32 characters")
        if not app_config.internal_api_token or len(app_config.internal_api_token) < 32:
            raise ValueError("INTERNAL_API_TOKEN must be set and at least 32 characters")

validate_config()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = app_config.django_secret
JWT_SECRET = app_config.jwt_secret

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = get_allowed_hosts()


# Managed database allowlists — exact-match membership, never regex-shaped, since these
# values are interpolated into generated Terraform HCL and secret/snapshot identifiers.
# RDS engines are pinned to MAJOR versions only: RDS retires minors on its own schedule
# (every exact minor pinned here was gone within months), and a major version makes AWS
# pick its current default minor at create time.
DATABASE_ENGINE_VERSIONS = {
    "postgres": {"15", "16", "17"},
    "mysql": {"8.0", "8.4"},
    "redis": {"7.1"},
    "docdb": {"5.0.0"},
}
DATABASE_INSTANCE_CLASSES = {
    "postgres": {"db.t3.micro", "db.t3.small", "db.t3.medium", "db.r6g.large"},
    "mysql": {"db.t3.micro", "db.t3.small", "db.t3.medium", "db.r6g.large"},
    "redis": {"cache.t3.micro", "cache.t3.small", "cache.t3.medium", "cache.r6g.large"},
    "docdb": {"db.t3.medium", "db.r6g.large"},
}
DATABASE_MIN_STORAGE_GB = 20
DATABASE_MAX_STORAGE_GB = 1000
MAX_DATABASES_PER_INFRA = int(os.environ.get('MAX_DATABASES_PER_INFRA', '10'))

# Sanity ceiling on Infrastructure.max_cpu/max_memory (vCPU / GB, the same units
# application-service validates alloted_cpu/alloted_memory against). These were never
# validated server-side; a caller could set an arbitrary or negative ceiling that no app
# could ever be scheduled under, or one large enough to be meaningless as a cap.
INFRA_MAX_CPU_VCPU = float(os.environ.get('INFRA_MAX_CPU_VCPU', '256'))
INFRA_MAX_MEMORY_GB = float(os.environ.get('INFRA_MAX_MEMORY_GB', '2048'))

# Per-user budget for the databases endpoints (F0) — see shared.ratelimit.budget. Keyed
# on request.user.id, independent of the gateway's per-IP limit and of other features'
# buckets, so a single user can't exhaust another feature's quota or vice versa.
RATE_BUDGET_DATABASES_LIMIT = int(os.environ.get('RATE_BUDGET_DATABASES_LIMIT', '60'))
RATE_BUDGET_DATABASES_WINDOW_SECONDS = int(os.environ.get('RATE_BUDGET_DATABASES_WINDOW_SECONDS', '60'))

# H6: a tighter per-user budget on top of `databases`, scoped to create/delete only (GET
# passes through uncharged — see shared.ratelimit.budget.rate_limited's `methods` param).
# Create/delete each provision or tear down a real RDS/ElastiCache/DocumentDB resource in
# the customer's account, so they warrant a much lower ceiling than the read-heavy general
# budget above.
RATE_BUDGET_DATABASES_WRITE_LIMIT = int(os.environ.get('RATE_BUDGET_DATABASES_WRITE_LIMIT', '10'))
RATE_BUDGET_DATABASES_WRITE_WINDOW_SECONDS = int(os.environ.get('RATE_BUDGET_DATABASES_WRITE_WINDOW_SECONDS', '300'))

# Per-user budget for the evidence-pack endpoint (F5) — an AssumeRole plus a handful of
# read-only IAM calls in the customer's account, requested rarely (an auditor pulling
# evidence, not a polling dashboard), so the default is much tighter than `databases`.
RATE_BUDGET_EVIDENCE_LIMIT = int(os.environ.get('RATE_BUDGET_EVIDENCE_LIMIT', '10'))
RATE_BUDGET_EVIDENCE_WINDOW_SECONDS = int(os.environ.get('RATE_BUDGET_EVIDENCE_WINDOW_SECONDS', '300'))

# Per-user budget for the exit-export endpoint (F6) — the heaviest read this service does
# per request (an internal call to application-service plus assembling a multi-file
# archive), requested even more rarely than the evidence pack. A separate, tighter
# one-per-infrastructure-per-hour gate (EXIT_EXPORT_PER_INFRA_WINDOW_SECONDS) sits behind
# the owner check so an invited ADMIN's denied attempt can never burn the owner's slot.
RATE_BUDGET_EXIT_EXPORT_LIMIT = int(os.environ.get('RATE_BUDGET_EXIT_EXPORT_LIMIT', '5'))
RATE_BUDGET_EXIT_EXPORT_WINDOW_SECONDS = int(os.environ.get('RATE_BUDGET_EXIT_EXPORT_WINDOW_SECONDS', '3600'))
EXIT_EXPORT_PER_INFRA_WINDOW_SECONDS = int(os.environ.get('EXIT_EXPORT_PER_INFRA_WINDOW_SECONDS', '3600'))
# How fresh the caller's JWT `iat` must be to download an export or complete exit —
# re-authentication for this operation specifically (plan/F6-exit-export.md Decisions).
EXIT_EXPORT_REAUTH_MAX_AGE_SECONDS = int(os.environ.get('EXIT_EXPORT_REAUTH_MAX_AGE_SECONDS', '600'))
# Timeout for the same-origin call to application-service's export-inventory endpoint.
# Kept well under the gateway's fixed 10s proxy timeout (gateway-service/app/services/
# proxy.py) so a slow upstream surfaces as this service's own 502, not a gateway 504.
EXIT_EXPORT_UPSTREAM_TIMEOUT_SECONDS = float(os.environ.get('EXIT_EXPORT_UPSTREAM_TIMEOUT_SECONDS', '6'))
# How long "Complete exit" waits for the platform DNS writer to confirm teardown before
# responding 202 instead of 200 — also bounded by the gateway's 10s proxy timeout.
EXIT_COMPLETE_DNS_TEARDOWN_TIMEOUT_SECONDS = int(os.environ.get('EXIT_COMPLETE_DNS_TEARDOWN_TIMEOUT_SECONDS', '7'))
# Per-user budget for the complete-exit endpoint — a one-time, high-consequence action, so
# the default is tighter than exit-export's own budget rather than reusing it.
RATE_BUDGET_COMPLETE_EXIT_LIMIT = int(os.environ.get('RATE_BUDGET_COMPLETE_EXIT_LIMIT', '5'))
RATE_BUDGET_COMPLETE_EXIT_WINDOW_SECONDS = int(os.environ.get('RATE_BUDGET_COMPLETE_EXIT_WINDOW_SECONDS', '3600'))

# Same-origin base URL for application-service, used only by the exit-export endpoint's
# server-to-server call (api/services/exit_export.py) — every other cross-service call in
# this codebase today is either a RabbitMQ event or gateway-proxied.
APPLICATION_SERVICE_URL = os.environ.get('APPLICATION_SERVICE_URL', 'http://localhost:8001')

# The Launchpad platform's own IAM identity, as trusted by the customer's role's trust
# policy (see app_scripts/create_aws_role.sh: LAUNCHPAD_PLATFORM_ACCOUNT_ID / _USER).
# Only used to verify a customer's live trust policy names the right principal
# (api/services/evidence_pack.py). No hard-coded default: this identifies which AWS
# principal a real drift check trusts, so a wrong default would be a silent security
# hole, not just a wrong answer. MODE=dev never makes a real AssumeRole (see
# api/cloud_providers/aws/authenticate.py) or a real evidence-pack drift check, so it
# alone gets a placeholder; every other deployment must set this explicitly.
_platform_principal_arn = os.environ.get('LAUNCHPAD_PLATFORM_PRINCIPAL_ARN')
if _platform_principal_arn:
    LAUNCHPAD_PLATFORM_PRINCIPAL_ARN = _platform_principal_arn
elif is_dev_mode(app_config.mode):
    LAUNCHPAD_PLATFORM_PRINCIPAL_ARN = "arn:aws:iam::000000000000:user/dev-placeholder"
else:
    raise ValueError(
        "LAUNCHPAD_PLATFORM_PRINCIPAL_ARN must be set outside MODE=dev — it names the AWS "
        "principal the evidence-pack live drift check trusts, and has no safe default."
    )

# Must be a user ARN, not just any non-empty string: api.cloud_providers.aws.
# platform_principal.platform_account_and_user() parses it into the
# LAUNCHPAD_PLATFORM_ACCOUNT_ID / LAUNCHPAD_PLATFORM_USER the dashboard hands customers
# for their trust policy. Failing that parse at request time instead of here would turn
# a config typo into a 500 (list/detail) or a 400 blamed on the caller (create). This
# check keeps it a boot-time failure, matching the "no safe default" rule above.
if not re.match(r'^arn:aws:iam::\d{12}:user/[^/]+$', LAUNCHPAD_PLATFORM_PRINCIPAL_ARN):
    raise ValueError(
        "LAUNCHPAD_PLATFORM_PRINCIPAL_ARN must be a user ARN of the form "
        f"arn:aws:iam::<12-digit account>:user/<name>, got {LAUNCHPAD_PLATFORM_PRINCIPAL_ARN!r}."
    )

# Per-user budget for the costs endpoint (F4). Lower than `databases`: unlike a database
# create/list, every cache-miss call here costs the customer $0.01 (Cost Explorer) and the
# dashboard has no reason to poll it as often as deploy status.
RATE_BUDGET_COSTS_LIMIT = int(os.environ.get('RATE_BUDGET_COSTS_LIMIT', '20'))
RATE_BUDGET_COSTS_WINDOW_SECONDS = int(os.environ.get('RATE_BUDGET_COSTS_WINDOW_SECONDS', '60'))

# F1b part 3b (custom domains): per-user budget for claim/verify/delete (each costs an
# AssumeRole plus at least one ACM/DNS call), and a per-infra cap on concurrently PENDING
# claims — without it, an attacker with one owned infra could flood a customer's AWS
# account with ACM RequestCertificate calls (one per claim) merely by claiming hostnames
# and never verifying them.
RATE_BUDGET_CUSTOM_DOMAINS_LIMIT = int(os.environ.get('RATE_BUDGET_CUSTOM_DOMAINS_LIMIT', '30'))
RATE_BUDGET_CUSTOM_DOMAINS_WINDOW_SECONDS = int(os.environ.get('RATE_BUDGET_CUSTOM_DOMAINS_WINDOW_SECONDS', '60'))
MAX_PENDING_CUSTOM_DOMAINS_PER_INFRA = int(os.environ.get('MAX_PENDING_CUSTOM_DOMAINS_PER_INFRA', '20'))

# Bounded query window for the costs endpoint — a customer-controlled start/end could
# otherwise page through years of Cost Explorer history at $0.01/request.
COST_QUERY_MAX_MONTHS = int(os.environ.get('COST_QUERY_MAX_MONTHS', '3'))

# EKS cost-estimate pricing constants (F4). No split cost allocation data exists for a
# Kubernetes pod, so the estimate is each app's alloted_cpu/alloted_memory (the values its
# pod's resource requests were set to) times AWS Fargate on-demand pricing, us-east-1,
# Linux/x86 — verified against https://aws.amazon.com/fargate/pricing/ and
# https://aws.amazon.com/eks/pricing/ on 2026-09-27; re-verify before relying on this
# against a real account (see plan/F4-cost-tagging.md Decisions).
COST_ESTIMATE_VCPU_HOUR_USD = float(os.environ.get('COST_ESTIMATE_VCPU_HOUR_USD', '0.040478'))
COST_ESTIMATE_GB_HOUR_USD = float(os.environ.get('COST_ESTIMATE_GB_HOUR_USD', '0.004446'))
COST_ESTIMATE_EKS_CONTROL_PLANE_HOUR_USD = float(os.environ.get('COST_ESTIMATE_EKS_CONTROL_PLANE_HOUR_USD', '0.10'))

# Single settings source for the platform's DNS zone apex. App URLs are
# {slug}.{dns_label}.{PLATFORM_BASE_DOMAIN}; the platform DNS writer (api/services/
# platform_dns/) and the custom-domain reserved-suffix check both read this one value
# rather than each defining their own.
#
# F1b part 3b (security pre-review §5): a fallback to 'launchpad.app' here was a fail-open
# spoofing hole — a customer could claim `evil.launchpad.app` as a "custom domain" on their
# own infra and the reserved-suffix check would use whatever this defaulted to, not the
# platform's real zone, if the two ever drifted. Unset now fails closed outside dev mode.
# MODE=dev gets a placeholder that can never collide with a real customer domain or the
# platform's own zone, so tests and non-AWS local dev don't need the var set.
_platform_base_domain = os.environ.get('PLATFORM_BASE_DOMAIN')
if _platform_base_domain:
    PLATFORM_BASE_DOMAIN = _platform_base_domain
elif is_dev_mode(app_config.mode):
    PLATFORM_BASE_DOMAIN = "launchpad.test"
else:
    raise ValueError(
        "PLATFORM_BASE_DOMAIN must be set outside MODE=dev — it is the platform's DNS zone "
        "apex and the reserved-suffix boundary for customer custom domains, and has no "
        "safe default."
    )

# Apex domain custom-domain hostnames must not be able to spoof, e.g. `evil.launchpad.app`.
# Matched against the normalized ASCII/punycode hostname — see
# api/models/custom_domain.py:normalize_hostname.
RESERVED_DOMAIN_SUFFIX = PLATFORM_BASE_DOMAIN

# A root domain PLATFORM_BASE_DOMAIN is delegated from, if any (e.g. PLATFORM_BASE_DOMAIN=
# "eu.launchpad.app" delegated from "launchpad.app") — a custom hostname equal to or under
# this is rejected too, alongside PLATFORM_BASE_DOMAIN itself.
#
# Deliberately optional, not required outside MODE=dev like PLATFORM_BASE_DOMAIN above:
# in this platform's actual DNS topology (see infra/platform-dns/README.md and
# docs/PLATFORM_DNS_ISOLATION.md), PLATFORM_BASE_DOMAIN *is* the platform's own zone apex,
# applied directly to a dedicated DNS account — it is not itself a sub-zone delegated from
# some larger domain this platform also controls. Forcing an operator to set this to a
# meaningless value in that (the normal) case would be worse than leaving it unset. Set it
# only if a future deployment's PLATFORM_BASE_DOMAIN ever becomes a delegated sub-zone of a
# larger root this platform still owns and must also keep customers off of.
PLATFORM_ROOT_DOMAIN = os.environ.get('PLATFORM_ROOT_DOMAIN') or None


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'shared.middleware.error_handler.ErrorHandlerMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # Temporarily disabled
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shared.middleware.internal_auth.InternalAuthMiddleware',
    'shared.middleware.authentication.JWTAuthMiddleware',
]

ROOT_URLCONF = 'core.urls'

APPEND_SLASH=True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_USER_MODEL = "api.User"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
db_config = DatabaseConfig.from_env()

from shared.resilience import get_db_pool_config

DATABASES = {
    "default": get_db_pool_config(db_config)
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

INTERNAL_AUTH_EXEMPT_PATHS = [
    "/health",
    "/api/v1/healthz",
    "/api/v1/liveness",
    "/api/v1/readiness",
    "/api/v1/docs/",
    "/api/v1/schema/",
    "/api/v1/infrastructures/onboarding/callback/",
    "/api/v1/infrastructures/policy-refresh/callback/",
]
INTERNAL_AUTH_HEADER_NAME = "X-INTERNAL-TOKEN"
INTERNAL_AUTH_TOKEN = app_config.internal_api_token

# Redis configuration
REDIS_HOST = app_config.redis_host
REDIS_PORT = app_config.redis_port
REDIS_PASSWORD = app_config.redis_password
REDIS_DB = app_config.redis_db

# EKS deployment target. EKS_ENABLED gates compute_type=eks at create AND at provision
# dispatch (the reaper/startup recovery re-enqueue independently of the create-time check).
EKS_ENABLED = os.environ.get('EKS_ENABLED', 'False').lower() == 'true'
# Comma-separated CIDRs allowed to reach an EKS cluster's public API endpoint.
# validate_eks_public_access_cidrs (api/services/terraform_worker.py's EKS config
# generation) hard-refuses an empty, malformed, or 0.0.0.0/0-equivalent list at
# provision time; the check below catches the same misconfiguration at boot instead of
# letting every EKS provision fail 2s in with no earlier signal.
EKS_PUBLIC_ACCESS_CIDRS = [
    c.strip() for c in os.environ.get('EKS_PUBLIC_ACCESS_CIDRS', '').split(',') if c.strip()
]
# MODE=dev never runs a real Terraform apply (see TerraformWorker.provision's mock path),
# so a placeholder/empty list there is harmless; every other deployment must set this
# correctly before the platform can provision any EKS infrastructure.
if EKS_ENABLED and not is_dev_mode(app_config.mode):
    try:
        validate_eks_public_access_cidrs(EKS_PUBLIC_ACCESS_CIDRS)
    except ValueError as exc:
        raise ValueError(
            f"EKS_ENABLED=true requires a valid EKS_PUBLIC_ACCESS_CIDRS (got "
            f"{os.environ.get('EKS_PUBLIC_ACCESS_CIDRS', '')!r}): {exc}"
        ) from exc

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'shared.auth.jwt_auth.MiddlewareJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'shared.errors.drf_handler.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Infrastructure Service API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

LOG_DIR = os.path.join(os.path.dirname(BASE_DIR), 'logs', 'infrastructure-service')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'shared': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
