services:
  postgres:
    ports:
      - "5433:5432"
  mysql:
    ports:
      - "3306:3306"
  mongo:
    ports:
      - "27017:27017"
  redis:
    ports:
      - "6379:6379"
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
