# Generated by Django 6.0.1 on 2026-01-28 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 2, 27, 17, 21, 43, 203888, tzinfo=datetime.timezone.utc)),
        ),
    ]
