# Generated by Django 6.0.1 on 2026-02-17 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_billing_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='user',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 19, 15, 55, 51, 467346, tzinfo=datetime.timezone.utc)),
        ),
    ]
