# Generated by Django 6.0.1 on 2026-02-19 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_infrastructure_user_infrastructure_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 21, 10, 44, 10, 582407, tzinfo=datetime.timezone.utc)),
        ),
    ]
