# Generated by Django 6.0.1 on 2026-02-19 10:56

import datetime
from django.db import migrations, models
import api.models.billing


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_invited_by_alter_billing_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due_date',
            field=models.DateField(default=api.models.billing.thirty_days_hence),
        ),
    ]
