"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from api.common.envs.application import app_config
from api.common.envs.database import db_config
from shared.mode import is_dev_mode

from core.allowed_hosts_config import get_allowed_hosts


# Validate critical configuration on startup
def validate_config():
    if not app_config.django_secret or len(app_config.django_secret) < 50:
        raise ValueError("DJANGO_SECRET must be set and at least 50 characters")
    if not app_config.jwt_secret or len(app_config.jwt_secret) < 32:
        raise ValueError("JWT_SECRET must be set and at least 32 characters")
    if not app_config.internal_api_token or len(app_config.internal_api_token) < 32:
        raise ValueError("INTERNAL_API_TOKEN must be set and at least 32 characters")
    # Signs the runtime-logs pagination cursor (customer CloudWatch/k8s pagination
    # tokens never travel to the client raw). A weak/default secret outside dev mode
    # would let a forged cursor widen another app's log window.
    if not is_dev_mode(app_config.mode):
        cursor_secret = os.environ.get("RUNTIME_LOGS_CURSOR_SECRET", "")
        if not cursor_secret or len(cursor_secret) < 32:
            raise ValueError("RUNTIME_LOGS_CURSOR_SECRET must be set and at least 32 characters outside dev mode")

validate_config()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = app_config.django_secret
JWT_SECRET = app_config.jwt_secret

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# Django's technical 500 page renders local variables from every frame — for the
# runtime-logs endpoint that includes the customer's own application log content.
# Outside dev mode that page must never be reachable.
if DEBUG and not is_dev_mode(app_config.mode):
    raise ValueError("DEBUG must not be enabled outside dev mode")

ALLOWED_HOSTS = get_allowed_hosts()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'shared.middleware.error_handler.ErrorHandlerMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shared.middleware.internal_auth.InternalAuthMiddleware',
    'shared.middleware.authentication.JWTAuthMiddleware',
    'api.middleware.user_verification.UserVerificationMiddleware'
]

# CSRF settings for API
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000').split(',')
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_USER_MODEL = "api.User"

INTERNAL_AUTH_TOKEN=app_config.internal_api_token

INTERNAL_AUTH_EXEMPT_PATHS = [
    "/health",
    "/api/v1/healthz",
    "/api/v1/liveness",
    "/api/v1/readiness",
    "/api/v1/docs/",
    "/api/v1/schema/",
]
# GitHub posts directly to the gateway from outside our network and won't carry the
# internal token; the per-app HMAC in the view is the trust boundary instead.
INTERNAL_AUTH_EXEMPT_PREFIXES = [
    "/api/v1/webhooks/",
]
INTERNAL_AUTH_HEADER_NAME = "X-INTERNAL-TOKEN"
INTERNAL_AUTH_TOKEN = app_config.internal_api_token

# Redis connection for shared.ratelimit.budget (per-user customer-call budgets), read at
# import time by that module — must exist before it's imported anywhere.
REDIS_HOST = app_config.redis_host
REDIS_PORT = int(app_config.redis_port)
REDIS_PASSWORD = app_config.redis_password
REDIS_DB = int(app_config.redis_db)

# Each request costs an AssumeRole plus a CloudWatch/k8s API call in the customer's own
# account — billed to them, consuming their API throttle. No gateway exemption.
RATE_BUDGET_RUNTIME_LOGS_LIMIT = int(os.environ.get('RATE_BUDGET_RUNTIME_LOGS_LIMIT', '30'))
RATE_BUDGET_RUNTIME_LOGS_WINDOW_SECONDS = int(os.environ.get('RATE_BUDGET_RUNTIME_LOGS_WINDOW_SECONDS', '60'))

# Higher than runtime logs: the dashboard polls this on an interval and the 30s response
# cache (api/services/app_metrics_service.py) absorbs most repeat requests within a window,
# so the budget only has to bound cache-miss traffic (new range, cache eviction, new app).
RATE_BUDGET_APP_METRICS_LIMIT = int(os.environ.get('RATE_BUDGET_APP_METRICS_LIMIT', '60'))
RATE_BUDGET_APP_METRICS_WINDOW_SECONDS = int(os.environ.get('RATE_BUDGET_APP_METRICS_WINDOW_SECONDS', '60'))

# Signs the runtime-logs pagination cursor; see validate_config() above for the
# outside-dev-mode length requirement. The dev fallback only ever runs under MODE=dev.
RUNTIME_LOGS_CURSOR_SECRET = os.environ.get('RUNTIME_LOGS_CURSOR_SECRET') or (
    "dev-only-runtime-logs-cursor-secret-not-for-prod" if is_dev_mode(app_config.mode) else ""
)

# Public-facing gateway URL used when generating webhook URLs to hand to GitHub.
# Normalized to scheme://host[:port] at load — a value with a trailing path/slash
# would otherwise produce malformed webhook URLs registered in GitHub.
def _origin_only(raw: str) -> str:
    from urllib.parse import urlparse
    parsed = urlparse(raw.strip())
    if parsed.scheme and parsed.netloc:
        return f"{parsed.scheme}://{parsed.netloc}"
    return raw.strip().rstrip("/")

PUBLIC_GATEWAY_URL = _origin_only(os.environ.get("PUBLIC_GATEWAY_URL", "http://localhost:8000"))

DJANGO_PORT = app_config.django_port

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

from shared.resilience import get_db_pool_config

DATABASES = {
    "default": get_db_pool_config(db_config)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'shared.auth.jwt_auth.MiddlewareJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'shared.errors.drf_handler.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Application Service API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Logging Configuration
LOG_DIR = os.path.join(os.path.dirname(BASE_DIR), 'logs', 'application-service')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        # These libraries log request/response detail (including CloudWatch/k8s API
        # bodies) at INFO — pinned to WARNING so runtime-log content never lands in the
        # platform's own log stream via a library logger the view code doesn't control.
        'botocore': {'handlers': ['console', 'file'], 'level': 'WARNING', 'propagate': False},
        'urllib3': {'handlers': ['console', 'file'], 'level': 'WARNING', 'propagate': False},
        'kubernetes': {'handlers': ['console', 'file'], 'level': 'WARNING', 'propagate': False},
    },
}

# Per-app ceiling for Kubernetes applications. Fargate has a fixed CPU/memory ladder
# topping out at 4 vCPU / 30 GB; Kubernetes has no such ladder, so it gets its own
# ceiling rather than silently inheriting Fargate's. The infrastructure's
# max_cpu/max_memory quota still applies on top of this.
EKS_MAX_APP_CPU = float(os.environ.get('EKS_MAX_APP_CPU', '64'))
EKS_MAX_APP_MEMORY = float(os.environ.get('EKS_MAX_APP_MEMORY', '256'))

# F1b part 3a: the platform DNS zone apex, mirrored from infrastructure-service's own
# PLATFORM_BASE_DOMAIN (must be the same value — see infrastructure-service/core/
# settings.py). Deliberately no 'launchpad.app' fallback the way that service's fail-open
# default has: an app hostname built here is shown to a customer as a live URL, so an
# unset/wrong value must produce no host URL at all rather than a hostname that never
# resolves. See api/common/host_url.py.
PLATFORM_BASE_DOMAIN = os.environ.get('PLATFORM_BASE_DOMAIN') or None

# F1b part 3b: AWS hard-caps a listener at 25 total certificates (default + SNI). Counting
# only SNI attachments (aws/alb.py:count_listener_certificates excludes IsDefault), 24
# leaves exactly one slot for the platform's own default/wildcard certificate — the same
# boundary AWS itself enforces (TooManyCertificatesException), reached here first with a
# clean 409 instead of relying solely on that exception surfacing through boto3.
MAX_SNI_CERTIFICATES_PER_LISTENER = int(os.environ.get('MAX_SNI_CERTIFICATES_PER_LISTENER', '24'))

# Same-origin base URL for infrastructure-service, used only by the custom-domains
# teardown path (api/services/custom_domain_routing.py) to best-effort notify it that an
# application was deleted so it can disable that application's CustomDomain rows and
# delete their ACM certificates — mirrors infrastructure-service's own
# APPLICATION_SERVICE_URL (used by its exit-export endpoint), the reverse direction.
INFRASTRUCTURE_SERVICE_URL = os.environ.get('INFRASTRUCTURE_SERVICE_URL', 'http://localhost:8002')

# F1b part 3a security review (B1): EKS host mode is gated behind an explicit opt-in,
# default ON since 2026-09-29. Unlike ECS (where a per-app :443 host-header forward rule
# and one infra-wide :80 wildcard redirect are the whole mechanism), EKS host mode depends
# on the AWS Load Balancer Controller honoring a per-Ingress `listen-ports` annotation to
# scope a host-only Ingress to HTTPS:443 and never attach its rule to the shared ALB's :80
# listener (see api/k8s/deployer.py:EKSDeployer._host_ingress_manifest). Verified on a real
# EKS Auto Mode cluster (REAL-AWS-VALIDATION.md, B1): the host rule exists only on :443.
# Set False to keep every EKS app on path URLs (`host_url_status` = eks_host_mode_disabled).
EKS_HOST_MODE_ENABLED = os.environ.get('EKS_HOST_MODE_ENABLED', 'True').lower() == 'true'

# H1: Application.envs is Fernet ciphertext at rest (api/fields.py,
# migration 0037_encrypt_application_envs). Comma-separated, newest first — MultiFernet
# encrypts under the first entry and decrypts under any of them, so rotate_envs_encryption_key
# can move existing rows onto a newly-prepended key without a flag day. MODE=dev falls back
# to a fixed, publicly-known key (load_keys logs a warning); every other deployment must set
# this explicitly, same as LAUNCHPAD_PLATFORM_PRINCIPAL_ARN in infrastructure-service.
from api.common.envs_encryption import load_keys as _load_envs_encryption_keys

APP_ENVS_ENCRYPTION_KEYS = _load_envs_encryption_keys(
    os.environ.get('APP_ENVS_ENCRYPTION_KEYS', ''), is_dev_mode(app_config.mode),
)
