"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from api.common.envs.application import app_config
from api.common.envs.database import db_config

from core.allowed_hosts_config import get_allowed_hosts


# Validate critical configuration on startup
def validate_config():
    if not app_config.django_secret or len(app_config.django_secret) < 50:
        raise ValueError("DJANGO_SECRET must be set and at least 50 characters")
    if not app_config.jwt_secret or len(app_config.jwt_secret) < 32:
        raise ValueError("JWT_SECRET must be set and at least 32 characters")
    if not app_config.internal_api_token or len(app_config.internal_api_token) < 32:
        raise ValueError("INTERNAL_API_TOKEN must be set and at least 32 characters")

validate_config()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = app_config.django_secret
JWT_SECRET = app_config.jwt_secret

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = get_allowed_hosts()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'rest_framework',
    'drf_spectacular',
]

MIDDLEWARE = [
    'shared.middleware.error_handler.ErrorHandlerMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shared.middleware.internal_auth.InternalAuthMiddleware',
    'shared.middleware.authentication.JWTAuthMiddleware',
    'api.middleware.user_verification.UserVerificationMiddleware'
]

# CSRF settings for API
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:3000').split(',')
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = not DEBUG

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_USER_MODEL = "api.User"

INTERNAL_AUTH_TOKEN=app_config.internal_api_token

INTERNAL_AUTH_EXEMPT_PATHS = [
    "/health",
    "/api/v1/healthz",
    "/api/v1/liveness",
    "/api/v1/readiness",
    "/api/v1/docs/",
    "/api/v1/schema/",
]
# GitHub posts directly to the gateway from outside our network and won't carry the
# internal token; the per-app HMAC in the view is the trust boundary instead.
INTERNAL_AUTH_EXEMPT_PREFIXES = [
    "/api/v1/webhooks/",
]
INTERNAL_AUTH_HEADER_NAME = "X-INTERNAL-TOKEN"
INTERNAL_AUTH_TOKEN = app_config.internal_api_token

# Public-facing gateway URL used when generating webhook URLs to hand to GitHub.
# Normalized to scheme://host[:port] at load — a value with a trailing path/slash
# would otherwise produce malformed webhook URLs registered in GitHub.
def _origin_only(raw: str) -> str:
    from urllib.parse import urlparse
    parsed = urlparse(raw.strip())
    if parsed.scheme and parsed.netloc:
        return f"{parsed.scheme}://{parsed.netloc}"
    return raw.strip().rstrip("/")

PUBLIC_GATEWAY_URL = _origin_only(os.environ.get("PUBLIC_GATEWAY_URL", "http://localhost:8000"))

DJANGO_PORT = app_config.django_port

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

from shared.resilience import get_db_pool_config

DATABASES = {
    "default": get_db_pool_config(db_config)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'shared.auth.jwt_auth.MiddlewareJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'shared.errors.drf_handler.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Application Service API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Logging Configuration
LOG_DIR = os.path.join(os.path.dirname(BASE_DIR), 'logs', 'application-service')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'app.log'),
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'api': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Per-app ceiling for Kubernetes applications. Fargate has a fixed CPU/memory ladder
# topping out at 4 vCPU / 30 GB; Kubernetes has no such ladder, so it gets its own
# ceiling rather than silently inheriting Fargate's. The infrastructure's
# max_cpu/max_memory quota still applies on top of this.
EKS_MAX_APP_CPU = float(os.environ.get('EKS_MAX_APP_CPU', '64'))
EKS_MAX_APP_MEMORY = float(os.environ.get('EKS_MAX_APP_MEMORY', '256'))
