"""Golden tests for the terraform root-config builders (H3 trust boundary).

GOLDEN_ECS is generated by main's own `_generate_config` (verified byte-identical at
merge time), so this pins the ECS builder to upstream behaviour rather than to whatever
the split produced. The ECS builder reads Database rows for its module blocks, hence
the django_db marks.

The ECS builder output is pinned string-identical to the pre-EKS generator; the EKS
builder is selected only by the compute_type argument (fed from the model column,
never from caller-settable vars), allowlists cluster_version, and hard-refuses an
open or empty public-endpoint CIDR list.
"""
from types import SimpleNamespace
from unittest.mock import patch

import pytest
from api.common import naming
from api.services import terraform_worker as tw_mod
from api.services.terraform_worker import TerraformWorker
from shared.enums.orchestrator import ComputeType

INFRA_ID = "11111111-2222-3333-4444-555555555555"
ACCOUNT_ID = "123456789012"
VARS = {"aws_region": "us-east-1", "owner": "user-1", "vpc_cidr": "10.0.0.0/16"}
ARGS = (INFRA_ID, "bucket-x", "table-x", "us-east-1")

GOLDEN_ECS = '''
terraform {
  backend "s3" {
    bucket         = "bucket-x"
    key            = "infra/11111111-2222-3333-4444-555555555555/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "table-x"
    encrypt        = true
  }
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">=5.13,<6.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">=3.6,<4.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
  
  default_tags {
    tags = {
      Environment        = "infra-11111111-c6426b96"
      InfraID            = "11111111-2222-3333-4444-555555555555"
      "launchpad:infra"  = "11111111-2222-3333-4444-555555555555"
      ManagedBy          = "launchpad"
      Owner              = "user-1"
    }
  }
}

module "vpc" {
  source      = "./modules/vpc"
  environment = "infra-11111111-c6426b96"
  vpc_cidr    = "10.0.0.0/16"
}

module "iam" {
  source          = "./modules/iam"
  environment     = "infra-11111111-c6426b96"
  db_secret_arns  = []
}

module "ecs" {
  source             = "./modules/ecs"
  environment        = "infra-11111111-c6426b96"
  vpc_id             = module.vpc.vpc_id
  private_subnet_ids = module.vpc.private_subnet_ids
  
  depends_on = [module.vpc]
}

module "alb" {
  source                 = "./modules/alb"
  environment            = "infra-11111111-c6426b96"
  vpc_id                 = module.vpc.vpc_id
  public_subnet_ids      = module.vpc.public_subnet_ids
  alb_security_group_id  = module.vpc.alb_security_group_id
  
  depends_on = [module.vpc]
}

module "ecr" {
  source      = "./modules/ecr"
  environment = "infra-11111111-c6426b96"
}

output "vpc_id" { value = module.vpc.vpc_id }
output "cluster_arn" { value = module.ecs.cluster_arn }
output "alb_arn" { value = module.alb.alb_arn }
output "alb_dns" { value = module.alb.alb_dns }
output "target_group_arn" { value = module.alb.target_group_arn }
output "ecr_repository_url" { value = module.ecr.repository_url }
output "ecs_task_execution_role_arn" { value = module.iam.ecs_task_execution_role_arn }
output "alb_security_group_id" { value = module.vpc.alb_security_group_id }
'''


@pytest.fixture
def eks_cidrs(settings):
    settings.EKS_PUBLIC_ACCESS_CIDRS = ["203.0.113.0/24", "198.51.100.7/32"]
    return settings


@pytest.mark.django_db
def test_ecs_config_is_string_identical_to_golden():
    assert TerraformWorker._generate_config_ecs(VARS, *ARGS) == GOLDEN_ECS


@pytest.mark.django_db
def test_dispatcher_selects_ecs_from_compute_type():
    config = TerraformWorker._generate_config(VARS, *ARGS, ComputeType.ECS_FARGATE, ACCOUNT_ID)
    assert config == GOLDEN_ECS


@pytest.mark.django_db
def test_dispatcher_ignores_compute_type_smuggled_via_vars():
    tainted = {**VARS, "compute_type": "eks"}
    config = TerraformWorker._generate_config(tainted, *ARGS, ComputeType.ECS_FARGATE, ACCOUNT_ID)
    assert config == GOLDEN_ECS


@pytest.mark.django_db
def test_default_tags_carry_launchpad_infra_with_the_full_infra_id():
    """The provider's default_tags applies to every resource it creates, including
    inside child modules (vpc/ecs/alb/ecr) — this is how cost_service.py's Cost Explorer
    Filter={"Tags": {"Key": "launchpad:infra", ...}} sees terraform-managed shared
    infrastructure at all, alongside the pre-existing InfraID tag other code already reads
    (terraform_worker.py's own `tag:InfraID` filters, eks_teardown.py). Never a truncated
    UUIDv7 prefix (CLAUDE.md) — must be the exact same full id as InfraID."""
    config = TerraformWorker._generate_config_ecs(VARS, *ARGS)
    assert f'"launchpad:infra"  = "{INFRA_ID}"' in config
    assert f'InfraID            = "{INFRA_ID}"' in config


def test_eks_config_shape(eks_cidrs):
    config = TerraformWorker._generate_config(VARS, *ARGS, ComputeType.EKS, ACCOUNT_ID)
    assert 'module "eks"' in config
    assert 'module "vpc"' in config
    assert 'module "iam"' in config
    assert 'module "ecr"' in config
    assert 'module "alb"' not in config
    assert 'module "ecs"' not in config
    assert 'enable_elb_subnet_tags = true' in config
    assert '">= 5.79"' in config
    # The cluster name must be exactly what eks_teardown resolves the cluster by;
    # if these drift the orphan reap deletes load balancers for a live cluster.
    assert f'cluster_name         = "{naming.environment_name(INFRA_ID)}"' in config
    assert f'environment          = "{naming.environment_name(INFRA_ID)}"' in config
    assert 'cluster_version      = "1.31"' in config
    assert f'"launchpad:infra"  = "{INFRA_ID}"' in config
    assert 'public_access_cidrs  = ["203.0.113.0/24", "198.51.100.7/32"]' in config
    assert f'arn:aws:iam::{ACCOUNT_ID}:role/LaunchpadDeploymentRole' in config
    assert 'output "cluster_name"' in config
    assert 'output "ecr_repository_url"' in config


def test_eks_config_allowlists_cluster_version(eks_cidrs):
    ok = TerraformWorker._generate_config(
        {**VARS, "cluster_version": "1.30"}, *ARGS, ComputeType.EKS, ACCOUNT_ID
    )
    assert 'cluster_version      = "1.30"' in ok
    for bad in ("1.28", "1.31 ", 'evil"', "latest"):
        with pytest.raises(ValueError, match="cluster_version"):
            TerraformWorker._generate_config(
                {**VARS, "cluster_version": bad}, *ARGS, ComputeType.EKS, ACCOUNT_ID
            )


def test_eks_config_validates_account_id(eks_cidrs):
    """account_id is interpolated into a quoted HCL argument. It is validated on the API
    create/update paths, but the worker reads it straight off the persisted row — so it is
    re-checked here, at the interpolation sink, like cluster_version and the CIDR list."""
    for bad in ('12345678901"', 'evil"\n  provisioner "local-exec" {}', "12345678901", "", "abcdefghijkl"):
        with pytest.raises(ValueError, match="account_id"):
            TerraformWorker._generate_config(VARS, *ARGS, ComputeType.EKS, bad)


@pytest.mark.parametrize("bad_cidrs", [
    [],
    ["203.0.113.0/24", "0.0.0.0/0"],
    ["::/0"],
    ["0.0.0.0/1", "128.0.0.0/1"],
    ["10.0.0.0/15"],
    ["not-a-cidr"],
])
def test_eks_config_refuses_empty_invalid_or_open_cidrs(settings, bad_cidrs):
    settings.EKS_PUBLIC_ACCESS_CIDRS = bad_cidrs
    with pytest.raises(ValueError, match="EKS_PUBLIC_ACCESS_CIDRS"):
        TerraformWorker._generate_config(VARS, *ARGS, ComputeType.EKS, ACCOUNT_ID)


@pytest.mark.parametrize("good_cidrs", [
    ["203.0.113.0/24"],
    ["203.0.113.0/32", "198.51.0.0/16"],
])
def test_eks_config_accepts_narrow_cidrs(settings, good_cidrs):
    settings.EKS_PUBLIC_ACCESS_CIDRS = good_cidrs
    config = TerraformWorker._generate_config(VARS, *ARGS, ComputeType.EKS, ACCOUNT_ID)
    assert "public_access_cidrs" in config


@pytest.mark.django_db
def test_exec_tf_env_allowlist(monkeypatch):
    monkeypatch.setenv("JWT_SECRET", "super-secret")
    monkeypatch.setenv("INTERNAL_API_TOKEN", "internal-secret")
    monkeypatch.setenv("TF_LOG", "TRACE")
    captured = {}

    def fake_run(cmd, cwd, capture_output, text, env, **kwargs):
        captured.clear()
        captured.update(env)
        return SimpleNamespace(returncode=0, stdout="{}", stderr="")

    with patch.object(tw_mod.subprocess, "run", fake_run):
        result = TerraformWorker._exec_tf(
            ["terraform", "output", "-json"],
            VARS,
            {"aws_access_key_id": "AKIATEST", "aws_secret_access_key": "s", "aws_session_token": "t"},
            INFRA_ID, "us-east-1", ACCOUNT_ID, ComputeType.ECS_FARGATE,
            ensure_backend=False,
        )

    assert result["success"]
    assert "JWT_SECRET" not in captured
    assert "INTERNAL_API_TOKEN" not in captured
    assert captured["AWS_ACCESS_KEY_ID"] == "AKIATEST"
    # TF_* is deliberately not passed through: TF_CLI_ARGS would inject terraform args.
    assert "TF_LOG" not in captured
    assert "PATH" in captured
    for key in captured:
        assert key in ("PATH", "HOME") or key.startswith(("TF_", "AWS_")), key


# ── F1b part 2: conditional 443 listener ────────────────────────────────────────────

VALID_CERT_ARN = f"arn:aws:acm:us-east-1:{ACCOUNT_ID}:certificate/12345678-1234-1234-1234-123456789012"


@pytest.mark.django_db
def test_enable_https_unset_is_byte_identical_to_golden():
    """Restates test_ecs_config_is_string_identical_to_golden through the dispatcher, with
    account_id threaded through — the new parameter must not perturb the no-TLS output."""
    config = TerraformWorker._generate_config_ecs(VARS, *ARGS, ACCOUNT_ID)
    assert config == GOLDEN_ECS


@pytest.mark.django_db
def test_enable_https_true_adds_listener_vars_and_output():
    tls_vars = {**VARS, "enable_https": True, "certificate_arn": VALID_CERT_ARN}
    config = TerraformWorker._generate_config_ecs(tls_vars, *ARGS, ACCOUNT_ID)

    assert "enable_https           = true" in config
    assert f'certificate_arn        = "{VALID_CERT_ARN}"' in config
    assert 'output "https_listener_arn" { value = module.alb.https_listener_arn }' in config
    # Nothing else in the module/output shape changed.
    assert config.replace(
        f'\n  enable_https           = true\n  certificate_arn        = "{VALID_CERT_ARN}"', ""
    ).replace(
        '\noutput "https_listener_arn" { value = module.alb.https_listener_arn }', ""
    ) == GOLDEN_ECS


@pytest.mark.django_db
def test_missing_certificate_arn_with_enable_https_leaves_output_unmodified():
    """enable_https alone (no cert_arn yet) must never emit the listener vars — the
    listener is only ever applied once ACM has actually issued something to point at."""
    tls_vars = {**VARS, "enable_https": True}
    config = TerraformWorker._generate_config_ecs(tls_vars, *ARGS, ACCOUNT_ID)
    assert config == GOLDEN_ECS


@pytest.mark.django_db
def test_hostile_certificate_arn_is_rejected_at_the_sink():
    """certificate_arn is a new interpolation sink — bound to the infra's own
    region+account, exactly like the EKS account_id sink above."""
    hostile_arns = [
        'arn:aws:acm:us-east-1:123456789012:certificate/x"\n  provisioner "local-exec" {}',
        f"arn:aws:acm:eu-west-1:{ACCOUNT_ID}:certificate/12345678-1234-1234-1234-123456789012",  # wrong region
        "arn:aws:acm:us-east-1:999999999999:certificate/12345678-1234-1234-1234-123456789012",  # wrong account
        f"arn:aws:acm:us-east-1:{ACCOUNT_ID}:certificate/not-a-uuid",
    ]
    for arn in hostile_arns:
        tls_vars = {**VARS, "enable_https": True, "certificate_arn": arn}
        with pytest.raises(ValueError, match="certificate_arn"):
            TerraformWorker._generate_config_ecs(tls_vars, *ARGS, ACCOUNT_ID)


@pytest.mark.django_db
def test_certificate_arn_requires_a_valid_account_id():
    tls_vars = {**VARS, "enable_https": True, "certificate_arn": VALID_CERT_ARN}
    for bad_account in (None, "", "not-12-digits"):
        with pytest.raises(ValueError, match="certificate_arn|account_id"):
            TerraformWorker._generate_config_ecs(tls_vars, *ARGS, bad_account)
